name: Sync with Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的git历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 检查是否已存在upstream远程仓库
          if ! git remote | grep -q upstream; then
            git remote add upstream https://github.com/alantang1977/IPTV_SuperB.git
          else
            git remote set-url upstream https://github.com/alantang1977/IPTV_SuperB.git
          fi

      - name: Run sync script
        run: python sync_upstream.py

      - name: Commit and push if changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync with upstream [skip ci]" && git push) 